-- SQL schema for Supabase
-- This script sets up the tables for users, properties, messages, and favorites.

create table if not exists users (
  id uuid default uuid_generate_v4() primary key,
  role text,
  name text,
  email text,
  phone text,
  kyc_status text
);

create table if not exists properties (
  id bigint generated by default as identity primary key,
  owner_id uuid references users(id) on delete cascade,
  title text not null,
  location text not null,
  price integer not null,
  bedrooms integer not null,
  images text[],
  description text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists messages (
  id bigint generated by default as identity primary key,
  property_id bigint references properties(id) on delete cascade,
  sender_id uuid references users(id) on delete cascade,
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists favorites (
  user_id uuid references users(id) on delete cascade,
  property_id bigint references properties(id) on delete cascade,
  primary key (user_id, property_id)
);
